name: Test
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'release')"
    steps:
      - name: 检出代码
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 rust
        uses: puniyu/setup-rust@68ccd3fb057ba764e9dea803f7d84cac69343b26 # main
        with:
          tools: just
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 单元测试
        run: |
          just test