name: Test
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'release')"
    steps:
      - name: 检出代码
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 rust
        uses: puniyu/setup-rust@3a99a7723dbc3d48d118dcaaf537801ed4bcab0e # main
        with:
          tools: just
          cache: true
          prefix-key: ${{ env.APP_NAME }}

      - name: 单元测试
        run: |
          just test